config/routes.rb
SampleApp::Application.routes.draw do

  get "sessions/new"

  resources :users do
    resources :microposts, :only => [:index]  
    member do
      get :following, :followers
    end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :password_resets, :only => [:new, :create, :show, :edit, :update]

  root :to  => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new' 
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
 

end

app/models/password_reset.rb
# == Schema Information
# Schema version: 20110124131446
#
# Table name: password_resets
#
#  id         :integer         not null, primary key
#  token      :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  email      :string(255)
#

require 'digest'

class PasswordReset < ActiveRecord::Base
  attr_accessible :email
  
  belongs_to :user
  
  validates :email, :presence => true
  
  validate :user_email_exists
  
  before_create :relate_entry, :generate_token, :activate_unique_request
  
  private
    
    def user_email_exists
      if User.find_by_email(email).nil?
        errors.add(:email, "does not relate to any user")
      end
    end
    
    def relate_entry
      user = User.find_by_email(email)
      self.user_id = user.id
    end
    
    def generate_token
      user = User.find_by_email(email)
      self.token = secure_hash("#{Time.now.utc}--#{user.encrypted_password}")
    end
    
    def activate_unique_request      
      old_active_requests = PasswordReset.where(:active => true, :user_id => self.user_id)
      if !old_active_requests.empty?
        old_active_requests.each do |request|
          request.active = false
          request.save
        end
      end
      self.active = true
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_filter :unsigned_user, :only => [:new, :create, :show, :edit, :update]
  
  # GET /password_resets
  # GET /password_resets.xml
  def index
    @password_resets = PasswordReset.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @password_resets }
    end
  end

  # GET /password_resets/1
  # GET /password_resets/1.xml
  def show
    @password_reset = PasswordReset.find(params[:id])
    @title = "Password Reset"
  end

  # GET /password_resets/new
  # GET /password_resets/new.xml
  def new
    @password_reset = PasswordReset.new
    @title = "Password Reset"
  end

  # GET /password_resets/1/edit
  def edit
    @password_reset = PasswordReset.find(params[:id])
    
    if @password_reset && @password_reset.active && @password_reset.token == params[:token]
      @title = "Password Reset"
    else
      redirect_to root_path
    end
  end

  # POST /password_resets
  # POST /password_resets.xml
  def create
    @password_reset = PasswordReset.new(params[:password_reset])    

    if @password_reset.save
      flash[:success] = "Your request has been processed successfully"
      user = User.find(@password_reset.user_id)
      UserMailer.password_reset_confirmation(@password_reset).deliver
      redirect_to @password_reset
    else
      @title = "Password Reset"
      render 'new'
    end
  end

  # PUT /password_resets/1
  # PUT /password_resets/1.xml
  def update
    @password_reset = PasswordReset.find(params[:id])
    token = params[:password_reset][:token]
    
    if @password_reset.active && token == @password_reset.token
      if @password_reset.user.update_attributes(params[:user])
        sign_in(@password_reset.user)
        flash[:success] = "Your password has been reset successfully"
        @password_reset.active = false
        @password_reset.save
        redirect_to root_path
      else
        render 'edit'
      end
    else
      redirect_to root_path
    end
  end

  # DELETE /password_resets/1
  # DELETE /password_resets/1.xml
  def destroy
    @password_reset = PasswordReset.find(params[:id])
    @password_reset.destroy

    respond_to do |format|
      format.html { redirect_to(password_resets_url) }
      format.xml  { head :ok }
    end
  end
  
  private
    def unsigned_user
      redirect_to root_path if signed_in?
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/_form_edit.html.erb
<%= form_for(@password_reset) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<%= f.hidden_field :token, :value => @password_reset.token %>
	<div class = "field">
		<%= label(:user, :password) %><br/>
		<%= text_field(:user, :password) %>	
	</div>
	<div class = "field">
		<%= label(:user, :password_confirmation) %><br/>
		<%= text_field(:user, :password_confirmation) %>	
	</div>
	<div class = "actions">
		<%= f.submit "Send", :disable_with => 'Sending...' %>
	</div>
<% end %>

app/views/password_resets/_form_new.html.erb
<%= form_for(@password_reset) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class = "field">
		<%= f.label :email, "Your email" %><br/>
		<%= f.text_field :email %>		
	</div>
	<div class = "actions">
		<%= f.submit "Reset password", :disable_with => 'Reset passwording...' %>
	</div>
<% end %>

app/views/password_resets/edit.html.erb
<h1>Password Reset</h1>

<%= render 'form_edit' %>

app/views/password_resets/index.html.erb
<h1>Listing password_resets</h1>

<table>
  <tr>
    <th>Token</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @password_resets.each do |password_reset| %>
  <tr>
    <td><%= password_reset.token %></td>
    <td><%= password_reset.user_id %></td>
    <td><%= link_to 'Show', password_reset %></td>
    <td><%= link_to 'Edit', edit_password_reset_path(password_reset) %></td>
    <td><%= link_to 'Destroy', password_reset, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Password reset', new_password_reset_path %>

app/views/password_resets/new.html.erb
<h1>Password Reset</h1>

<%= render 'form_new' %>

app/views/password_resets/show.html.erb
<h1>Password Reset</h1>

<p>
	An email has been sent to the following address: <b><%= @password_reset.email %></b>
</p>

<p>
	Please click the link inside to reset your password
</p>